// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdXsQfJPo4rnJhUEK6NH4-bxuf5tWZJT0',
    appId: '1:386479265223:web:70dc135d8fb092be42f5e2',
    messagingSenderId: '386479265223',
    projectId: 'dairy-tooolkit',
    authDomain: 'dairy-tooolkit.firebaseapp.com',
    storageBucket: 'dairy-tooolkit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW5TEJ5JWrGmU9MOSNSEV3tIDx43fPvS4',
    appId: '1:386479265223:android:9ff3a343dbb13b7f42f5e2',
    messagingSenderId: '386479265223',
    projectId: 'dairy-tooolkit',
    storageBucket: 'dairy-tooolkit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SaMiDHMrBeYKM2hNeSc7WVXMYsiwJuw',
    appId: '1:386479265223:ios:9f7843a499d3a01e42f5e2',
    messagingSenderId: '386479265223',
    projectId: 'dairy-tooolkit',
    storageBucket: 'dairy-tooolkit.firebasestorage.app',
    iosBundleId: 'com.example.dairyFarmerToolkit',
  );
}
